set.seed(1)
beta <- sample(c(0.5, 0.5, -0.5, -0.5, rep(0, 46)))
dat <- hdrm::gen_data(50, 50, beta = beta)
fit <- ncvreg::ncvreg(dat$X, dat$y, lambda.min = 0.2)
png("../assets/ncvreg.png", pointsize = 16, res = 72 * 1.5, type = "cairo-png")
par(mar = c(4, 4, 0.05, 0.5))
plot(fit, bty = "n", las = 1)
dev.off()
system("mogrify -resize 200x ../assets/ncvreg.png")
