name: Update my People page entry
description: Request an update to your information on my website
title: "People page update: <your name>"
labels: ["people-update"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for keeping your info up to date!

  - type: textarea
    id: yaml
    attributes:
      label: Your entry (edit this block)
      description: |
        Paste your current block from people.yml and edit what you'd like changed.
        Example:
      value: |
        - id: patrick-breheny
          name: Patrick Breheny
          status: current
          affiliation: PhD student, University of Iowa, Department of Biostatistics
          url: (optional)
      render: yaml
    validations:
      required: true

  - type: input
    id: photo_link
    attributes:
      label: Photo link (optional)
      description: |
        If you'd like to update your photo, paste a public link here (Dropbox, Google Drive, personal site, etc.)
        OR attach an image below.
    validations:
      required: false

  - type: dropdown
    id: photo_source
    attributes:
      label: Photo
      description: Choose one option for your photo. (A photo is required.)
      options:
        - Use my department photo
        - I'll provide a link to a photo
        - I'll upload a photo to this issue
        - Please remove my photo (use initials only)
    validations:
      required: true

  - type: input
    id: photo_link
    attributes:
      label: Photo link (if you chose “link” above)
      description: A direct link to an image file works best (jpg/png). Share links are fine too.
      placeholder: https://...
    validations:
      required: false

  - type: textarea
    id: photo_upload
    attributes:
      label: Upload photo (if you chose “upload” above)
      description: |
        You can drag-and-drop an image here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Photo notes**
        - Photos display as small circles (~100×100 px)
        - If you upload a large photo, I may crop it
        - If you prefer a specific crop, upload a square image
        
  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      options:
        - label: I consent to this information being displayed publicly on Patrick's website.
          required: true
