source("htmlExport.R")
source("render.R")
D1 <- read.csv("cv.csv", stringsAsFactors=FALSE)
D2 <- read.delim("cv-extra.txt", stringsAsFactors=FALSE)
render("pubs.html", "../publications.html")
render("res.html", "../research.html")
