library(data.table)
library(stringr)
source("_publications/html-export.r")
source("_publications/md-export.r")
source("_publications/render.r")

dat <- merge(
  fread("_publications/cv.csv"),
  fread("_publications/cv-extra.txt"),
  by = "Identifier",
  all.x = TRUE
)

# Render
render("_publications/pubs.md", "publications.md", dat)
render("_publications/res.md", "research.md", dat)
perl_cmd = r"(perl -p0i -e "s{---\n\n}{compiled: true\n---\n\n[//]: # Do not edit this file -- edit pubs/pubs.md instead!\n\n}")"
system(glue::glue("{perl_cmd} publications.md"))
perl_cmd = r"(perl -p0i -e "s{---\n\n}{compiled: true\n---\n\n[//]: # Do not edit this file -- edit pubs/res.md instead!\n\n}")"
system(glue::glue("{perl_cmd} research.md"))
