library(data.table)
library(stringr)
source("pubs/html-export.r")
source("pubs/md-export.r")
source("pubs/render.r")

dat <- merge(
  fread("pubs/cv.csv"),
  fread("pubs/cv-extra.txt"),
  by = "Identifier",
  all.x = TRUE
)

# Render
render("pubs/pubs.md", "publications.md", dat)
render("pubs/res.md", "research.md", dat)
perl_cmd = r"(perl -p0i -e "s{---\n\n}{compiled: true\n---\n\n[//]: # Do not edit this file -- edit pubs/pubs.md instead!\n\n}")"
system(glue::glue("{perl_cmd} publications.md"))
perl_cmd = r"(perl -p0i -e "s{---\n\n}{compiled: true\n---\n\n[//]: # Do not edit this file -- edit pubs/res.md instead!\n\n}")"
system(glue::glue("{perl_cmd} research.md"))
